### ISSUE TITLE
Ask for something

### ISSUE THREAD

**Issue by qingfengxulai199** [zshyang/brain#1]
Hello, I am a student from China. I have recently been learning graphics related codes for brain conformal mapping, but I can’t find some learning code online. Could you give me some learning methods or information? Thank you.

**Comment by zshyang** [comment]
Hi, 
I am not good at brain conformal mapping. But I think [some other students](https://gsl.lab.asu.edu/people/) in our lab are very good at it. Maybe you could try to reach out to them. Thank you!
Best regards!
